### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by kosicki123** [KrauseFx/what-terminal-is-felix-using#3]
Hey KrauseFx, I wonder if you could update the readme with the theme used on your setup!

Thanks a lot!

**Comment by KrauseFx** [comment]
@kosicki123 Sorry, not sure what you mean, it should all be on the README

**Comment by KrauseFx** [comment]
Oh, you mean the colors?

**Comment by KrauseFx** [comment]
I updated the docs to describe the color scheme https://github.com/KrauseFx/what-terminal-is-felix-using Please let me know if that helps :+1:

**Comment by kosicki123** [comment]
Yeah, that's what I needed!

Thanks @KrauseFx
