### ISSUE TITLE
How do you setup your terminal?

### ISSUE THREAD

**Issue by andreasklinger** [KrauseFx/what-terminal-is-felix-using#4]
Just saw the screenshot in the repo. Looks awesome. What shell/font is this?

**Comment by KrauseFx** [comment]
Please check out the [README](https://github.com/KrauseFx/what-terminal-is-felix-using#readme) of the project, in particular the list of tools/options that are being used:

> - I use [iTerm2](https://www.iterm2.com/) instead of the Stock terminal Mac app
> - I use [oh-my-zshell](https://github.com/robbyrussell/oh-my-zsh)
> - ...
> - I use the [Meslo Powerline Font](https://github.com/powerline/fonts/blob/master/Meslo/Meslo%20LG%20M%20DZ%20Regular%20for%20Powerline.otf) as you need a font that supports the directory characters for `powerline`
